### PR TITLE
WIP: updating docker-base

### PR DESCRIPTION
**Pull request by kingdonb**
Needs a second glance before merging, I will also fix the commit messages before this gets merged

### CODE REVIEW

**Review by Cryptophobia — CHANGES_REQUESTED** [review]
Can you fix the commit msg @kingdonb ? https://docs.teamhephy.com/contributing/submitting-a-pull-request/#commit-style

**Comment by kingdonb** [comment]
I fixed the commit message to abide by the commit style guide

**Review by Cryptophobia — APPROVED** [review]

**Comment by Cryptophobia** [comment]
LGTM

Thank you for taking care of this @kingdonb !

**Comment by felixbuenemann** [comment]
Looks like this was never released?

If you check https://hub.docker.com/r/hephy/base/tags it only has v0.3.6 tag which uses Xenial.

**Comment by Cryptophobia** [comment]
Released a new tag as v0.4.0 here: https://github.com/teamhephy/docker-base/tree/v0.4.0

And pushing to hephy/base dockerhub now.

**Pull request merged**
